### PR TITLE
Neural Filter sample

### PR DESCRIPTION
**Pull request by zrthxn**
Closes: #23 

Screenshot (1)

### CODE REVIEW

**Comment by zrthxn** [comment]
@ErinFinnegan @kerrishotts Right now I've only created the JS side of the code. Should I also build a HTML UI for the plugin window/panel?

**Review by kerrishotts — CHANGES_REQUESTED** [review]
Looks really good, although I'd suggest adding a parameter or two that the user could adjust -- just to show the pattern for those who want something that's dynamic. Maybe something for the focal distance in the haze filter?

**Comment by zrthxn** [comment]
Yes so I should add a UI, alright. 
Although since the changes won't have preview it wouldn't make visual sense... But I'll add a slider anyway

**Comment by zrthxn** [comment]
@kerrishotts Added a basic UI with sliders for parameters

**Review by frankyapolda41 — APPROVED** [review]

**Review by frankyapolda41 — APPROVED** [review]

**Pull request merged**
